#
# - id: '1588893016815'
#   alias: menu.click
#   description: ''
#   trigger: []
#   condition: []
#   action:
#   - data:
#       command: menu
#       entity_id: remote.living_room_apple_tv
#     entity_id: remote.living_room_apple_tv
#     service: remote.send_command

- id: 'atvmenu'
  alias: menu.click
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      command: memu
      entity_id: remote.living_room_apple_tv
    entity_id: remote.living_room_apple_tv
    service: remote.send_command

# - id: '1588893454390'
#   alias: left.click
#   description: ''
#   trigger: []
#   condition: []
#   action:
#   - data:
#       command: left
#       entity_id: remote.living_room_apple_tv
#     entity_id: remote.living_room_apple_tv
#     service: remote.send_command
- id: 'newcustom'
  alias: left.click
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      command: left
      entity_id: remote.living_room_apple_tv
    entity_id: remote.living_room_apple_tv
    service: remote.send_command
- id: '1588893677501'
  alias: right.click
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      command: right
      entity_id: remote.living_room_apple_tv
    entity_id: remote.living_room_apple_tv
    service: remote.send_command
- id: '1588894393629'
  alias: up.click
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      command: up
      entity_id: remote.living_room_apple_tv
    entity_id: remote.living_room_apple_tv
    service: remote.send_command
- id: '1588894418468'
  alias: down.click
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      command: down
      entity_id: remote.living_room_apple_tv
    entity_id: remote.living_room_apple_tv
    service: remote.send_command
- id: '1588896133904'
  alias: enter.click
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      command: select
      entity_id: remote.living_room_apple_tv
    entity_id: remote.living_room_apple_tv
    service: remote.send_command
