title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.ken
      - entity: sun.sun
    cards:
      - type: media-control
        entity: media_player.living_room_apple_tv
      - type: entities
        entities:
          - remote.living_room_apple_tv
        title: remote
      - type: weather-forecast
        entity: weather.home

# Custom Apple TV buttons
      - entity: media_player.living_room_apple_tv
        type: media-control
      - entities:
          - media_player.living_room_apple_tv
        show_header_toggle: false
        type: entities
      - entity: media_player.living_room_apple_tv
        type: media-control
      - cards:
          - cards:
              - entity: remote.living_room_apple_tv
                hold_action:
                  action: none
                icon: 'mdi:arrow-left'
                name: Left knop
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: automation.trigger
                  service_data:
                    entity_id: automation.left_click
                type: button
              - entity: remote.living_room_apple_tv
                hold_action:
                  action: none
                icon: 'mdi:apple'
                name: Enter klik
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: automation.trigger
                  service_data:
                    entity_id: automation.enter_click
                type: button
              - entity: remote.living_room_apple_tv
                hold_action:
                  action: none
                icon: 'mdi:arrow-right'
                name: Right klik
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: automation.trigger
                  service_data:
                    entity_id: automation.right_click
                type: button
            type: horizontal-stack
          - cards:
              - entity: remote.living_room_apple_tv
                hold_action:
                  action: none
                icon: 'mdi:arrow-up'
                name: up knop
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: automation.trigger
                  service_data:
                    entity_id: automation.up_click
                type: button
              - entity: remote.living_room_apple_tv
                hold_action:
                  action: none
                icon: 'mdi:menu'
                name: Menu knop
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: automation.trigger
                  service_data:
                    entity_id: automation.menu_click
                type: button
              - entity: remote.kamer_bas
                hold_action:
                  action: none
                icon: 'mdi:arrow-down'
                name: down knop
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: automation.trigger
                  service_data:
                    entity_id: automation.down_click
                type: button
            type: horizontal-stack
        type: vertical-stack
